services:
  postgre:
    image: postgres:15
    container_name: quizora_db
    restart: always
    environment:
      POSTGRES_DB: quizora_db
      POSTGRES_USER: quizora_user
      POSTGRES_PASSWORD: quizora_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongo:
    image: mongo:6.0
    container_name: quizora_mongo
    restart: always
    env_file:
      - ./backend/backend/.env.local
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - ./backend/backend/.env.docker:/app/backend/backend/.env.docker
    ports:
      - "8000:8000"
      - "5678:5678" 
    depends_on:
      - postgre
      - mongo
    env_file:
      - ./backend/backend/.env.docker
    environment:
      - DJANGO_ENV=docker

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run dev -- --host

volumes:
  pgdata:
  static_volume:
  mongodata:
