# Generated by Django 5.2.3 on 2025-07-12 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mock_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('FIB', 'Fill in the Blank'), ('SA', 'Short Answer'), ('ESSAY', 'Essay / Long Answer'), ('CODE', 'Code Snippet'), ('IDF', 'Identification'), ('MATCH', 'Matching'), ('ORDER', 'Ordering'), ('MA', 'Multiple Answers'), ('OTH', 'Other')], max_length=10)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock_quizzes.mockquiz')),
            ],
        ),
    ]
