# Generated by Django 5.2.3 on 2025-07-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_quizzes', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
